### ISSUE TITLE
Help Invalidating displayLink

### ISSUE THREAD

**Issue by diegojmaldonado** [originaluser2/Circle-Loader#1]
Hi! great job and It was indeed very clarifier. 

I'm facing an issue and really hope you can help me with, the thing is that i need to invalidate the displayLink from the UIViewController. Any suggestions?

Thanks in advanced.

**Comment by hamishknight** [comment]
Sure, I have added the necessary code allowing you to do this by calling startAnimation() or stopAnimation() on the TeethLoaderView

**Comment by diegojmaldonado** [comment]
Thanks
